### ISSUE TITLE
definition

### ISSUE THREAD

**Issue by adammaj1** [anvaka/streamlines#8]
Hi
Thx for great code.
Here vector field is defined as a function. Is it possible to define vector field as an array of floating point values ?
Like here:
https://en.wikibooks.org/wiki/Fractals/Mathematics/Vector_field#Potential_of_Mandelbrot_set

TIA

**Comment by tetonpeaks** [comment]
I have the same question. I have (u, v) or (Vx, Vy) computed from a finite volume method. It would really help me along if this was doable rather than functions. Do you have any suggestions?

Good code.

**Comment by anvaka** [comment]
It is somewhat possible, but you will have to provide values for the points that are outside of the discrete set. So your function could do something like bilinear interpolation to provide values.

**Comment by anvaka** [comment]
Here is an example that you can paste into https://anvaka.github.io/streamlines/ . 

``` js
class Grid {
  constructor(size) {
    // this array of points can come outside too. Here we just initialize it with some random
    // function values. You can also use totally `Math.random()` values and get
    // something like a vector field of perlin noise
    this.points = [];
    for (let i = 0; i < size; ++i) {
      let arr = [];
      for (let j = 0; j < size; ++j) {
        arr.push({
          x: Math.sin(i), // Math.random() - .5,
          y: Math.cos(j), // Math.random() - .5
        })
      }
      this.points.push(arr);
    }
  }
  
  velocityAtPoint(p) {
    if (p.x < 0 || p.y < 0 || Math.ceil(p.x) >= this.points.length ||
        Math.ceil(p.y) >= this.points.length) {
      // out of range.
      return {
        x: -1, y: -1
      };
    }
    let bottomLeft, bottomRight, topRight, topLeft;
    bottomLeft = this.points[Math.floor(p.x)][Math.floor(p.y)];
    bottomRight = this.points[Math.ceil(p.x)][Math.floor(p.y)];
    topRight = this.points[Math.ceil(p.x)][Math.ceil(p.y)];
    topLeft = this.points[Math.floor(p.x)][Math.ceil(p.y)];

    let x = p.x - Math.floor(p.x);
    let y = p.y - Math.floor(p.y);
    let vx = (1 - x) * (1 - y) * bottomLeft.x + x * (1 - y) * bottomRight.x + x * y * topRight.x + (1 - x) * y * topLeft.x;
    let vy = (1 - x) * (1 - y) * bottomLeft.y + x * (1 - y) * bottomRight.y + x * y * topRight.y + (1 - x) * y * topLeft.y;
    return { x: vx, y: vy };
  }
}

let g = new Grid(10);

function getVelocity(p) {
  return g.velocityAtPoint({
    x: p.x + 4.5, 
    y: p.y + 4.5
  });
}
```

The function uses bilinear interpolation to calculate the velocity at the point `p`. This involves calculating the weighted average of the velocities at the four corners of the square based on the position of the point `p`. The weighting factor is determined by the `x` and `y` coordinates of the point `p`.
